#!/usr/bin/env bash
# DFIR preflight — inventory of actually-available SIFT tooling.
# Prints a markdown report to stdout. Safe to tee into ./analysis/preflight.md.
# No side effects on evidence; does not require sudo.

set -u  # unset-var is an error
# no set -e: we expect some commands to be missing, that's the point

UTC_NOW="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
HOST="$(hostname 2>/dev/null || echo unknown)"
KERNEL="$(uname -r 2>/dev/null || echo unknown)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")"
INSTALLER_SCRIPT="${SCRIPT_DIR}/install-tools.sh"
MISSING_COUNT=0

# ---------- helpers ----------
bin_check() {
    # bin_check <command> — tries --version, -V, -v in that order; suppresses error banners
    local cmd="$1"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        printf "| \`%s\` | MISSING | — | — |\n" "$cmd"
        (( MISSING_COUNT++ )) || true
        return 1
    fi
    local path; path="$(command -v "$cmd")"
    local ver=""
    for varg in --version -V -v; do
        local out; out="$("$cmd" "$varg" 2>&1 | head -n1 | tr -d '\r')"
        # reject usage/error lines
        if [[ -n "$out" ]] && [[ "$out" != *invalid* ]] && [[ "$out" != *Unknown* ]] \
           && [[ "$out" != *usage:* ]] && [[ "$out" != *Usage:* ]]; then
            ver="$out"
            break
        fi
    done
    printf "| \`%s\` | OK | \`%s\` | %s |\n" "$cmd" "$path" "${ver:-present}"
    return 0
}

pkg_check() {
    # pkg_check <dpkg-pkg-name>
    local pkg="$1"
    if dpkg -s "$pkg" >/dev/null 2>&1; then
        local ver; ver="$(dpkg -s "$pkg" 2>/dev/null | awk -F': ' '/^Version:/ {print $2; exit}')"
        printf "| \`%s\` | INSTALLED | %s |\n" "$pkg" "${ver:-n/a}"
        return 0
    else
        printf "| \`%s\` | MISSING | — |\n" "$pkg"
        (( MISSING_COUNT++ )) || true
        return 1
    fi
}

py_check() {
    # py_check <module>
    local mod="$1"
    if python3 -c "import $mod" >/dev/null 2>&1; then
        local ver; ver="$(python3 -c "import $mod; print(getattr($mod,'__version__','n/a'))" 2>/dev/null)"
        printf "| \`%s\` | OK | %s |\n" "$mod" "${ver:-n/a}"
        return 0
    else
        printf "| \`%s\` | MISSING | — |\n" "$mod"
        (( MISSING_COUNT++ )) || true
        return 1
    fi
}

path_check() {
    # path_check <path> <label>
    local p="$1"; local label="$2"
    if [[ -e "$p" ]]; then
        printf "| %s | PRESENT | \`%s\` |\n" "$label" "$p"
        return 0
    else
        printf "| %s | MISSING | \`%s\` |\n" "$label" "$p"
        (( MISSING_COUNT++ )) || true
        return 1
    fi
}

# ---------- header ----------
cat <<EOF
# SIFT Preflight — $UTC_NOW

**Host:** \`$HOST\`
**Kernel:** \`$KERNEL\`
**Python:** \`$(python3 --version 2>&1 | tr -d '\r')\`

> Generated by \`$SCRIPT_PATH\`. Re-run on every
> new SIFT instance — do not trust prior results from other hosts.

---

## Core CLI tools
| Tool | Status | Path | Version |
|---|---|---|---|
EOF

bin_check fls || true
bin_check icat || true
bin_check ils || true
bin_check blkls || true
bin_check mactime || true
bin_check mmls || true
bin_check fsstat || true
bin_check tsk_recover || true
bin_check img_stat || true
bin_check ewfinfo || true
bin_check ewfverify || true
bin_check ewfmount || true
bin_check log2timeline.py || true
bin_check psort.py || true
bin_check pinfo.py || true
bin_check bulk_extractor || true
bin_check photorec || true
bin_check yara || true
bin_check yarac || true
bin_check chainsaw || true
bin_check hayabusa || true
bin_check evtx_dump || true
bin_check dotnet || true
bin_check wine || true
bin_check tshark || true
bin_check capinfos || true
bin_check mergecap || true
bin_check editcap || true
bin_check tcpdump || true
bin_check tcpflow || true
bin_check ngrep || true
bin_check zeek || true
bin_check zeek-cut || true
bin_check suricata || true
bin_check suricata-update || true
bin_check nfdump || true
bin_check jq || true

# Suricata ET Open ruleset presence + signature count
SURICATA_RULES_PATH="/var/lib/suricata/rules/suricata.rules"
if [[ -s "$SURICATA_RULES_PATH" ]]; then
    sig_count=$(grep -c '^alert' "$SURICATA_RULES_PATH" 2>/dev/null || echo 0)
    printf "| ET Open ruleset | OK | \`%s\` | %s signatures |\n" "$SURICATA_RULES_PATH" "$sig_count"
else
    printf "| ET Open ruleset | MISSING | \`%s\` | run \`sudo suricata-update\` |\n" "$SURICATA_RULES_PATH"
    (( MISSING_COUNT++ )) || true
fi

cat <<'EOF'

## Python
### Python executable & bootstrap
| Tool | Status | Path | Version |
|---|---|---|---|
EOF

bin_check python3 || true
bin_check pip3 || true
# Confirm `python3 -m pip` as a fallback invocation path
if python3 -m pip --version >/dev/null 2>&1; then
    printf "| \`python3 -m pip\` | OK | (module) | %s |\n" "$(python3 -m pip --version 2>&1 | head -n1)"
else
    printf "| \`python3 -m pip\` | MISSING | — | — |\n"
    (( MISSING_COUNT++ )) || true
fi

cat <<'EOF'

### Python libraries (forensic parsers)
| Module | Status | Version |
|---|---|---|
EOF

py_check regipy || true
py_check Evtx || true              # python-evtx (module: Evtx)
py_check yara || true              # yara-python bindings
py_check pyewf || true
py_check pytsk3 || true
py_check impacket || true
py_check construct || true
py_check scapy || true             # programmatic packet manipulation
py_check dpkt || true              # lightweight pcap parsing

cat <<'EOF'

## Volatility 3
| Path | Status |
|---|---|
EOF

# Discover Volatility 3 without hardcoding a version. Search common /opt layouts,
# then fall back to vol/vol.py on PATH, then to the volatility3 Python module.
VOL3_PATH=""
for cand in /opt/volatility3*/vol.py /opt/volatility3/vol.py; do
    [[ -f "$cand" ]] && VOL3_PATH="$cand" && break
done
if [[ -z "$VOL3_PATH" ]]; then
    for c in vol.py vol; do
        if command -v "$c" >/dev/null 2>&1; then
            # reject Volatility 2 (/usr/local/bin/vol.py on stock SIFT)
            if "$c" --help 2>&1 | grep -qiE 'volatility 3|framework 2\.'; then
                VOL3_PATH="$(command -v "$c")"
                break
            fi
        fi
    done
fi
if [[ -z "$VOL3_PATH" ]] && python3 -c 'import volatility3' >/dev/null 2>&1; then
    VOL3_PATH="(python module: volatility3)"
fi
if [[ -n "$VOL3_PATH" ]]; then
    printf "| Volatility 3 vol.py | PRESENT | \`%s\` |\n" "$VOL3_PATH"
else
    printf "| Volatility 3 vol.py | MISSING | searched \`/opt/volatility3*/vol.py\`, PATH, python module |\n"
    (( MISSING_COUNT++ )) || true
fi

# Memory Baseliner — co-located with vol.py per CLAUDE.md
BASELINE_PATH=""
for cand in /opt/volatility3*/baseline.py /opt/volatility3/baseline.py; do
    [[ -f "$cand" ]] && BASELINE_PATH="$cand" && break
done
if [[ -n "$BASELINE_PATH" ]]; then
    printf "| Memory Baseliner | PRESENT | \`%s\` |\n" "$BASELINE_PATH"
else
    printf "| Memory Baseliner | MISSING | searched \`/opt/volatility3*/baseline.py\` |\n"
    (( MISSING_COUNT++ )) || true
fi

cat <<'EOF'

## EZ Tools (Zimmerman)
| Path | Status |
|---|---|
EOF
path_check /opt/zimmermantools "EZ Tools root" || EZ_ROOT_MISSING=1
path_check /opt/zimmermantools/PECmd.dll "PECmd.dll" || true
path_check /opt/zimmermantools/RBCmd.dll "RBCmd.dll" || true
path_check /opt/zimmermantools/MFTECmd.dll "MFTECmd.dll" || true
path_check /opt/zimmermantools/AppCompatCacheParser.dll "AppCompatCacheParser.dll" || true
path_check /opt/zimmermantools/AmcacheParser.dll "AmcacheParser.dll" || true
path_check /opt/zimmermantools/LECmd.dll "LECmd.dll" || true
path_check /opt/zimmermantools/JLECmd.dll "JLECmd.dll" || true
path_check /opt/zimmermantools/SBECmd.dll "SBECmd.dll" || true
path_check /opt/zimmermantools/SrumECmd.dll "SrumECmd.dll" || true
path_check /opt/zimmermantools/EvtxeCmd/EvtxECmd.dll "EvtxECmd.dll" || true
path_check /opt/zimmermantools/RECmd/RECmd.dll "RECmd.dll" || true
path_check /opt/zimmermantools/SQLECmd/SQLECmd.dll "SQLECmd.dll" || true

cat <<'EOF'

## dpkg packages (forensic)
| Package | Status | Version |
|---|---|---|
EOF
pkg_check libewf-tools || true   # GIFT package providing ewfinfo/ewfverify/ewfmount
pkg_check libewf || true         # modern libewf shared lib (GIFT)
pkg_check sleuthkit || true
pkg_check libtsk19 || true
pkg_check plaso-tools || true
pkg_check bulk-extractor || true
pkg_check python3-evtx || true
pkg_check python3-pip || true
pkg_check dotnet-runtime-9.0 || true
pkg_check tshark || true
pkg_check wireshark-common || true
pkg_check tcpdump || true
pkg_check tcpflow || true
pkg_check ngrep || true
pkg_check suricata || true
pkg_check suricata-update || true
pkg_check nfdump || true
pkg_check jq || true

cat <<'EOF'

## Environment
| Check | Result |
|---|---|
EOF

# sudo — non-interactive test (does NOT prompt for password)
if sudo -n true >/dev/null 2>&1; then
    printf "| sudo (non-interactive) | OK — usable without TTY |\n"
else
    printf "| sudo (non-interactive) | BLOCKED — TTY required; \`sudo apt install\` cannot be driven from this shell |\n"
    (( MISSING_COUNT++ )) || true
fi

# Network — 3s budget; treat non-zero as blocked
if command -v curl >/dev/null 2>&1; then
    if curl -s --max-time 3 -o /dev/null -w '%{http_code}' https://pypi.org/ 2>&1 | grep -qE '^(200|301|302)$'; then
        printf "| outbound https to pypi.org | REACHABLE |\n"
    else
        printf "| outbound https to pypi.org | BLOCKED or permission-gated — cannot self-install Python libs |\n"
        (( MISSING_COUNT++ )) || true
    fi
else
    printf "| outbound https to pypi.org | curl not installed — skipped |\n"
    (( MISSING_COUNT++ )) || true
fi

# Disk space on $HOME
printf "| disk free on \$HOME | %s available |\n" "$(df -h "$HOME" 2>/dev/null | awk 'NR==2 {print $4}')"

# Evidence dir writability test (in current project only)
if [[ -d ./analysis ]]; then
    if touch ./analysis/.preflight_write_test 2>/dev/null; then
        rm -f ./analysis/.preflight_write_test
        printf "| \`./analysis/\` writable | YES |\n"
    else
        printf "| \`./analysis/\` writable | NO — case-init.sh needed |\n"
    fi
else
    printf "| \`./analysis/\` | does not exist — run \`case-init.sh\` |\n"
fi

cat <<EOF

---

## Bootstrap Remediation
| Check | Result |
|---|---|
EOF
if [[ -x "$INSTALLER_SCRIPT" ]]; then
    printf "| installer script | FOUND at \`%s\` |\n" "$INSTALLER_SCRIPT"
else
    printf "| installer script | NOT FOUND (expected: \`%s\`) |\n" "$INSTALLER_SCRIPT"
    (( MISSING_COUNT++ )) || true
fi

cat <<EOF

### Suggested commands

\`\`\`bash
# Inventory missing components with no changes
bash ${INSTALLER_SCRIPT} --check

# Install only missing components
sudo bash ${INSTALLER_SCRIPT}
\`\`\`

---

## Per-skill readiness

| Skill | Status | Rationale |
|---|---|---|
EOF

# sleuthkit — needs fls + mactime + EITHER libewf (modern, GIFT) OR libewf2 (stock)
if command -v fls >/dev/null 2>&1 && command -v mactime >/dev/null 2>&1 \
   && { dpkg -s libewf >/dev/null 2>&1 || dpkg -s libewf2 >/dev/null 2>&1; }; then
    printf "| sleuthkit | GREEN | fls + mactime + libewf present; E01 read directly |\n"
else
    printf "| sleuthkit | RED | missing fls/mactime/libewf — install \`sleuthkit\` + \`libewf\` (or \`libewf2\`) |\n"
fi

# plaso-timeline
if command -v log2timeline.py >/dev/null 2>&1; then
    printf "| plaso-timeline | GREEN | log2timeline.py on PATH |\n"
else
    printf "| plaso-timeline | RED | no log2timeline.py — install \`plaso-tools\` from GIFT PPA |\n"
fi

# memory-analysis — uses the VOL3_PATH discovered above
if [[ -n "$VOL3_PATH" ]]; then
    printf "| memory-analysis | GREEN | Volatility 3 present (\`%s\`) |\n" "$VOL3_PATH"
else
    printf "| memory-analysis | RED | Volatility 3 missing — searched /opt/volatility3*/vol.py, PATH, python module |\n"
fi

# yara-hunting
if command -v yara >/dev/null 2>&1; then
    printf "| yara-hunting | GREEN | yara CLI present |\n"
else
    printf "| yara-hunting | RED | yara missing — install \`yara\` |\n"
fi

# sigma-hunting — green when chainsaw is present (preferred);
# yellow when only hayabusa is available (less of an orchestrator fit);
# red when neither is on PATH.
if command -v chainsaw >/dev/null 2>&1; then
    printf "| sigma-hunting | GREEN | chainsaw on PATH |\n"
elif command -v hayabusa >/dev/null 2>&1; then
    printf "| sigma-hunting | YELLOW | hayabusa present but chainsaw missing — install \`chainsaw\` for orchestrator fit |\n"
else
    printf "| sigma-hunting | RED | neither chainsaw nor hayabusa on PATH — install one (see CLAUDE.md tool table) |\n"
fi

# windows-artifacts — green if EZ Tools present, yellow if only fallbacks
if [[ -d /opt/zimmermantools ]] && command -v dotnet >/dev/null 2>&1; then
    printf "| windows-artifacts | GREEN | EZ Tools + dotnet present |\n"
elif python3 -c 'import Evtx, regipy' >/dev/null 2>&1; then
    printf "| windows-artifacts | YELLOW | no EZ Tools but python-evtx+regipy present — structured parse OK |\n"
else
    printf "| windows-artifacts | YELLOW | EZ Tools + regipy + python-evtx all missing — use dfir-bootstrap/parsers/ fallbacks |\n"
fi

# network-forensics — green when full toolchain present AND ET Open ruleset
# is populated; YELLOW if Suricata is installed but ET Open is missing (the
# IDS pass would run with an empty ruleset).
if command -v tshark >/dev/null 2>&1 && command -v zeek >/dev/null 2>&1 \
   && command -v suricata >/dev/null 2>&1; then
    if [[ -s "$SURICATA_RULES_PATH" ]]; then
        printf "| network-forensics | GREEN | tshark + zeek + suricata + ET Open ruleset all present |\n"
    else
        printf "| network-forensics | YELLOW | tshark + zeek + suricata present but ET Open ruleset MISSING — Suricata IDS pass would run with no signatures; \`sudo suricata-update\` |\n"
    fi
elif command -v tshark >/dev/null 2>&1; then
    printf "| network-forensics | YELLOW | tshark present but zeek/suricata missing — display-filter analysis only; install \`zeek\` + \`suricata\` for full coverage |\n"
else
    printf "| network-forensics | YELLOW | tshark/zeek/suricata absent — fall back to .claude/skills/network-forensics/parsers/ (stdlib pcap/zeek/suricata triage) |\n"
fi

cat <<'EOF'

---

## Key fallbacks if any row above is YELLOW/RED

- **E01 without ewf-tools:** Sleuth Kit reads E01 directly. `mmls /path/to/img.E01`,
  `fls -o <offset> /path/to/img.E01`, `icat -o <offset> /path/to/img.E01 <inode>` all
  work as long as `libewf2` is installed. Do NOT waste time on `ewfmount`. Formal
  `ewfverify` integrity check is the only thing you truly lose.
- **No EZ Tools / no regipy / no python-evtx:** use
  `.claude/skills/dfir-bootstrap/parsers/rb_parse.py`,
  `prefetch_parse.py`, `hive_strings.py`, and `evtx_strings.py`. They are stdlib-only.
- **No pip + no network:** ask the user to `sudo apt install python3-regipy
  python3-evtx ewf-tools` before continuing. These are packaged in SIFT's base repo.
- **sudo blocked:** do not attempt interactive sudo. Work within the read-only
  constraints of the shell you have.

EOF

printf "\n## Machine-readable skill status\n"
printf "<!-- grep for SKILL_STATUS: lines only; dpkg MISSING rows are informational -->\n\n"

# sleuthkit
if command -v fls >/dev/null 2>&1 && command -v mactime >/dev/null 2>&1 \
   && { dpkg -s libewf >/dev/null 2>&1 || dpkg -s libewf2 >/dev/null 2>&1; }; then
    printf "SKILL_STATUS:sleuthkit=GREEN\n"
else
    printf "SKILL_STATUS:sleuthkit=RED\n"
fi

# plaso-timeline
if command -v log2timeline.py >/dev/null 2>&1; then
    printf "SKILL_STATUS:plaso-timeline=GREEN\n"
else
    printf "SKILL_STATUS:plaso-timeline=RED\n"
fi

# memory-analysis — uses VOL3_PATH discovered above
if [[ -n "$VOL3_PATH" ]]; then
    printf "SKILL_STATUS:memory-analysis=GREEN\n"
else
    printf "SKILL_STATUS:memory-analysis=RED\n"
fi

# yara-hunting
if command -v yara >/dev/null 2>&1; then
    printf "SKILL_STATUS:yara-hunting=GREEN\n"
else
    printf "SKILL_STATUS:yara-hunting=RED\n"
fi

# sigma-hunting
if command -v chainsaw >/dev/null 2>&1; then
    printf "SKILL_STATUS:sigma-hunting=GREEN\n"
elif command -v hayabusa >/dev/null 2>&1; then
    printf "SKILL_STATUS:sigma-hunting=YELLOW\n"
else
    printf "SKILL_STATUS:sigma-hunting=RED\n"
fi

# windows-artifacts
if [[ -d /opt/zimmermantools ]] && command -v dotnet >/dev/null 2>&1; then
    printf "SKILL_STATUS:windows-artifacts=GREEN\n"
elif python3 -c 'import Evtx, regipy' >/dev/null 2>&1; then
    printf "SKILL_STATUS:windows-artifacts=YELLOW\n"
else
    printf "SKILL_STATUS:windows-artifacts=YELLOW\n"
fi

# network-forensics
if command -v tshark >/dev/null 2>&1 && command -v zeek >/dev/null 2>&1 \
   && command -v suricata >/dev/null 2>&1; then
    if [[ -s "$SURICATA_RULES_PATH" ]]; then
        printf "SKILL_STATUS:network-forensics=GREEN\n"
    else
        printf "SKILL_STATUS:network-forensics=YELLOW\n"
    fi
elif command -v tshark >/dev/null 2>&1; then
    printf "SKILL_STATUS:network-forensics=YELLOW\n"
else
    printf "SKILL_STATUS:network-forensics=RED\n"
fi

if [[ "$MISSING_COUNT" -eq 0 ]]; then
    printf "\n## Preflight Summary\n\nAll tracked checks are present.\n"
else
    printf "\n## Preflight Summary\n\nFound %s missing/blocked check row(s). Use the installer flow above, then re-run preflight.\n" "$MISSING_COUNT"
fi
